### ISSUE TITLE
Build failed by android-ndk-r11c

### ISSUE THREAD

**Issue by is** [android-rooting-tools/android_run_root_shell#35]
I follows the instruction in README.

when I run `ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk`

I got the error message from make
```
[armeabi] Compile thumb  : run_root_shell <= main.c
./main.c:14:29: fatal error: device_database.h: No such file or directory
 #include "device_database.h"
                             ^
compilation terminated.
/is/ws/android-ndk-r11c/build/core/build-binary.mk:460: recipe for target '/root/src/android_run_root_shell/obj/local/armeabi/objs/run_root_shell/main.o' failed
make: *** [/root/src/android_run_root_shell/obj/local/armeabi/objs/run_root_shell/main.o] Error 1
```

I'm sure TARGET_C_INCLUDES defined in Android.mk doesn't work properly.
The actual build command is
```
/is/ws/android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -MMD -MP -MF /root/src/android_run_root_shell/obj/local/armeabi/objs/run_root_shell/main.o.d -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -I. -DANDROID  -Wa,--noexecstack -Wformat -Werror=format-security    -isystem /is/ws/android-ndk-r11c/platforms/android-9/arch-arm/usr/include -c  ./main.c -o /root/src/android_run_root_shell/obj/local/armeabi/objs/run_root_shell/main.o
```
The device_database include directory option is missing.

I don't know why and how to resolve the problem.

I wonder which NDK version was used to build.

**Comment by xarkes** [comment]
Hi, I have the same problem, someone should fix it. As a temp fix I edited the C file to the correct path to the header (but fixing the Android.mk should be better)

**Comment by connorbode** [comment]
Links for r10e NDK:

- OSX: https://dl.google.com/android/repository/android-ndk-r12b-darwin-x86_64.zip
- Windows 32-bit: https://dl.google.com/android/repository/android-ndk-r10e-windows-x86.zip
- Windows 64-bit: https://dl.google.com/android/repository/android-ndk-r10e-windows-x86_64.zip
- Linux: https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip

**Comment by xarkes** [comment]
Maybe someone should add it into the readme as a requirement or warning
